// src/lib/mockData.ts
//
// Temporary mock data used to render the Browse and Listing Detail
// pages until the backend /api/listings endpoints are implemented.
// Replace calls to these with apiFetch('/api/listings') etc.

import { Listing } from '@/types';

export const priceTickerData = [
  { label: 'COPPER', ar: 'نحاس', range: '8.50 - 9.20' },
  { label: 'ALUMINUM', ar: 'ألمنيوم', range: '3.10 - 3.80' },
  { label: 'STEEL', ar: 'حديد', range: '0.90 - 1.20' },
  { label: 'BRASS', ar: 'نحاس أصفر', range: '6.40 - 7.10' },
  { label: 'PET PLASTIC', ar: 'بلاستيك PET', range: '0.60 - 0.95' },
  { label: 'CARDBOARD', ar: 'كرتون', range: '0.20 - 0.35' },
  { label: 'E-WASTE (MIXED)', ar: 'نفايات إلكترونية', range: '2.00 - 5.50' },
  { label: 'LEAD', ar: 'رصاص', range: '2.80 - 3.40' },
];

export const mockListings: Listing[] = [
  {
    id: '1',
    sellerId: 'u1',
    title: 'Mixed copper wire, clean',
    description: 'Stripped copper wire from electrical rewiring project, sorted and clean.',
    materialType: 'METAL',
    subtype: 'Copper',
    estimatedWeightKg: 120,
    pricePerKg: 8.8,
    pricingType: 'FIXED',
    photos: [],
    status: 'ACTIVE',
    address: 'Tripoli, Souq Al Jumaa',
    createdAt: '2026-06-10T09:00:00Z',
    seller: { id: 'u1', name: 'Ahmed Trading Co.' },
  },
  {
    id: '2',
    sellerId: 'u2',
    title: 'Aluminum scrap from window frames',
    description: 'Approx. 300kg of aluminum window frame offcuts, mostly clean.',
    materialType: 'METAL',
    subtype: 'Aluminum',
    estimatedWeightKg: 300,
    pricePerKg: null,
    pricingType: 'BID',
    photos: [],
    status: 'ACTIVE',
    address: 'Benghazi, Industrial Zone',
    createdAt: '2026-06-12T14:30:00Z',
    seller: { id: 'u2', name: 'Libya Build Supplies' },
  },
  {
    id: '3',
    sellerId: 'u3',
    title: 'PET plastic bottles, baled',
    description: '500kg baled PET bottles, sorted by color.',
    materialType: 'PLASTIC',
    subtype: 'PET',
    estimatedWeightKg: 500,
    pricePerKg: 0.75,
    pricingType: 'FIXED',
    photos: [],
    status: 'ACTIVE',
    address: 'Misrata',
    createdAt: '2026-06-11T11:00:00Z',
    seller: { id: 'u3', name: 'Green Cycle Misrata' },
  },
  {
    id: '4',
    sellerId: 'u4',
    title: 'Used laptops and circuit boards',
    description: 'Mixed lot of 40 non-functional laptops with boards intact.',
    materialType: 'ELECTRONICS',
    subtype: 'E-waste',
    estimatedWeightKg: 85,
    pricePerKg: null,
    pricingType: 'BID',
    photos: [],
    status: 'ACTIVE',
    address: 'Tripoli, Hay Andalus',
    createdAt: '2026-06-13T08:15:00Z',
    seller: { id: 'u4', name: 'Sara Electronics' },
  },
  {
    id: '5',
    sellerId: 'u5',
    title: 'Cardboard and paper offcuts',
    description: 'Bulk cardboard from packaging warehouse, dry storage.',
    materialType: 'PAPER',
    subtype: 'Cardboard',
    estimatedWeightKg: 800,
    pricePerKg: 0.28,
    pricingType: 'FIXED',
    photos: [],
    status: 'ACTIVE',
    address: 'Zawiya',
    createdAt: '2026-06-09T16:45:00Z',
    seller: { id: 'u5', name: 'Atlas Packaging' },
  },
  {
    id: '6',
    sellerId: 'u6',
    title: 'Steel rebar offcuts',
    description: 'Construction site offcuts, various lengths, some rust.',
    materialType: 'METAL',
    subtype: 'Steel',
    estimatedWeightKg: 1200,
    pricePerKg: 1.05,
    pricingType: 'FIXED',
    photos: [],
    status: 'ACTIVE',
    address: 'Tripoli, Tajura',
    createdAt: '2026-06-08T12:00:00Z',
    seller: { id: 'u6', name: 'Nour Construction' },
  },
];
